# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('kurs_otwarcia', models.FloatField()),
                ('kurs_max', models.FloatField()),
                ('kurs_min', models.FloatField()),
                ('kurs_biezacy', models.FloatField()),
                ('obrot', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dane',
            unique_together=set([('nazwa', 'data')]),
        ),
    ]
