# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_rogue_app', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
