# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_rogue_app', '0003_auto_20170529_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.IntegerField()),
                ('value', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_rogue_app.Spolka')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_played_company1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_played_company2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_played_company3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_played_company4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_played_company5',
        ),
        migrations.AddField(
            model_name='playercompany',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_rogue_app.Player'),
        ),
    ]
