# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_rogue_app', '0004_auto_20170531_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('value', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_rogue_app.Spolka')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_rogue_app.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='playercompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='playercompany',
            name='player',
        ),
        migrations.DeleteModel(
            name='PlayerCompany',
        ),
    ]
